--Sectors Table
INSERT INTO sectors (name) VALUES	
	('Energy'),
	('Materials'),
	('Industrials'),
	('Consumer Discretionary'),
	('Consumer Staples'),
	('Health Care'),
	('Financials'),
	('Information Technology'),
	('Communication Services'),
	('Utilities'),
	('Real Estate'),
	('Other');


--Industry Groups Table
INSERT INTO industry_groups (name, sector_id) VALUES	
	('Energy', 1),
	('Materials', 2),
	('Capital Goods', 3),
	('Commercial & Professional Services', 3),
	('Transportation', 3),
	('Automobiles & Components', 4),
	('Consumer Durables & Apparel', 4),
	('Consumer Services', 4),
	('Retailing', 4),
	('Food & Staples Retailing', 5),
	('Food, Beverage & Tobacco', 5),
	('Household & Personal Products', 5),
	('Health Care Equipment & Services', 6),
	('Pharmaceuticals & Biotechnology & Life Sciences', 6),
	('Banks', 7),
	('Diversified Financials', 7),
	('Insurance', 7),
	('Software & Services', 8),
	('Technology Hardware & Equipment', 8),
	('Semiconductors & Semiconductor Equipment', 8),
	('Telecommunication Services', 9),
	('Media & Entertainment', 9),
	('Utilities', 10),
	('Real Estate', 11),
	('Other', 12);


--Parent-Industries Table
INSERT INTO parent_industries (name, industry_group_id) VALUES	
	('Energy Equipment & Services', 1),
	('Oil, Gas & Consumable Fuels', 1),
	('Chemicals', 2),
	('Construction Materials', 2),
	('Containers & Packaging', 2),
	('Metals & Mining', 2),
	('Paper & Forest Products', 2),
	('Aerospace & Defense', 3),
	('Building Products', 3),
	('Construction & Engineering', 3),
	('Electrical Equipment', 3),
	('Industrial Conglomerates', 3),
	('Machinery', 3),
	('Trading Companies & Distributors', 3),
	('Commercial Services & Supplies', 4),
	('Professional Services', 4),
	('Air Freight & Logistics', 5),
	('Airlines', 5),
	('Marine', 5),
	('Road & Rail', 5),
	('Transportation Infrastructure', 5),
	('Auto Components', 6),
	('Automobiles', 6),
	('Household Durables', 7),
	('Leisure Products', 7),
	('Textiles, Apparel & Luxury Goods', 7),
	('Hotels, Restaurants & Leisure', 8),
	('Diversified Consumer Services', 8),
	('Distributors', 9),
	('Internet & Direct Marketing Retail', 9),
	('Multiline Retail', 9),
	('Specialty Retail', 9),
	('Food & Staples Retailing', 10),
	('Beverages', 11),
	('Food Products', 11),
	('Tobacco', 11),
	('Household Products', 12),
	('Personal Products', 12),
	('Health Care Equipment & Supplies', 13),
	('Health Care Providers & Services', 13),
	('Health Care Technology', 13),
	('Biotechnology', 14),
	('Pharmaceuticals', 14),
	('Life Sciences Tools & Services', 14),
	('Banks', 15),
	('Thrifts & Mortgage Finance', 15),
	('Diversified Financial Services', 16),
	('Consumer Finance', 16),
	('Capital Markets', 16),
	('Mortgage Real Estate Investment Trusts (REITs)', 16),
	('Insurance', 17),
	('IT Services', 18),
	('Software', 18),
	('Communications Equipment', 19),
	('Technology Hardware, Storage & Peripherals', 19),
	('Electronic Equipment, Instruments & Components', 19),
	('Semiconductors & Semiconductor Equipment', 20),
	('Diversified Telecommunication Services', 21),
	('Wireless Telecommunication Services', 21),
	('Media', 22),
	('Entertainment', 22),
	('Interactive Media & Services', 22),
	('Electric Utilities', 23),
	('Gas Utilities', 23),
	('Multi-Utilities', 23),
	('Water Utilities', 23),
	('Independent Power & Renewable Electricity Producers', 23),
	('Equity Real Estate Investment Trusts (REITs)', 24),
	('Real Estate Management & Development', 24),
	('Other', 25);


--Industries - Table
INSERT INTO industries (name, definition, parent_industry_id) VALUES	
	('Oil & Gas Drilling', 'Drilling contractors or owners of drilling rigs that contract their services for drilling wells.', 1),
	('Oil & Gas Equipment & Services', 'Manufacturers of equipment, including drilling rigs and equipment, and providers of supplies and services to companies involved in the drilling, evaluation and completion of oil and gas wells.', 1),
	('Integrated Oil & Gas', 'Integrated oil companies engaged in the exploration and production of oil and gas, as well as at least one other significant activity in either refining, marketing and transportation, or chemicals.', 2),
	('Oil & Gas Exploration & Production', 'Companies engaged in the exploration and production of oil and gas not classified elsewhere.', 2),
	('Oil & Gas Refining & Marketing', 'Companies engaged in the refining and marketing of oil, gas and/or refined products not classified in the Integrated Oil & Gas or Independent Power Producers & Energy Traders sub-industries.', 2),
	('Oil & Gas Storage & Transportation', 'Companies engaged in the storage and/or transportation of oil, gas and/or refined products. Includes diversified midstream natural gas companies facing competitive markets, oil and refined product pipelines, coal slurry pipelines and oil & gas shipping companies.', 2),
	('Coal & Consumable Fuels', 'Companies primarily involved in the production and mining of coal, related products and other consumable fuels related to the generation of energy. Excludes companies primarily producing gases classified in the Industrial Gases sub-industry.', 2),
	('Commodity Chemicals', 'Companies that primarily produce industrial chemicals and basic chemicals. Including but not limited to plastics, synthetic fibers, films, commodity-based paints and pigments, explosives and petrochemicals. Excludes chemical companies classified in the Diversified Chemicals, Fertilizers & Agricultural Chemicals, Industrial Gases, or Specialty Chemicals sub-industries.', 3),
	('Diversified Chemicals', 'Manufacturers of a diversified range of chemical products not classified in the Industrial Gases, Commodity Chemicals, Specialty Chemicals or Fertilizers & Agricultural Chemicals sub-industries.', 3),
	('Fertilizers & Agricultural Chemicals', 'Producers of fertilizers, pesticides, potash or other agriculture-related chemicals not classified elsewhere.', 3),
	('Industrial Gases', 'Manufacturers of industrial gases.', 3),
	('Specialty Chemicals', 'Companies that primarily produce high value-added chemicals used in the manufacture of a wide variety of products, including but not limited to fine chemicals, additives, advanced polymers, adhesives, sealants and specialty paints, pigments and coatings.', 3),
	('Construction Materials', 'Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified in the Building Products sub-industry.', 4),
	('Metal & Glass Containers', 'Manufacturers of metal, glass or plastic containers. Includes corks and caps.', 5),
	('Paper Packaging', 'Manufacturers of paper and cardboard containers and packaging.', 5),
	('Aluminum, Metals & Mining', 'Producers of aluminum and related products, including companies that mine or process bauxite and companies that recycle aluminum to produce finished or semi-finished products. Excludes companies that primarily produce aluminum building materials classified in the Building Products sub-industry.', 6),
	('Diversified Metals & Mining', 'Companies engaged in the diversified production or extraction of metals and minerals not classified elsewhere. Including, but not limited to, nonferrous metal mining (except bauxite) salt and borate mining, phosphate rock mining, and diversified mining operations. Excludes iron ore mining, classified in the Steel Sub-Industry, bauxite mining, classified in the Aluminum Sub-Industry, and coal mining, classified in either the Steel or Coal & Consumable Fuels Sub-Industries.', 6),
	('Copper, Metals & Mining', 'Companies involved primarily in copper ore mining.', 6),
	('Gold, Metals & Mining', 'Producers of gold and related products, including companies that mine or process gold and the South African finance houses which primarily invest in, but do not operate, gold mines.', 6),
	('Precious Metals & Minerals', 'Companies mining precious metals and minerals not classified in the Gold sub-industry. Includes companies primarily mining latinum.', 6),
	('Silver, Metals & Mining', 'Companies primarily mining silver. Excludes companies classified in the Gold or Precious Metals and Minerals Sub-Industries.', 6),
	('Steel, Metals & Mining', 'Producers of iron and steel and related products, including metallurgical (coking) coal mining used for steel production.', 6),
	('Forest Products', 'Manufacturers of timber and related wood products. Includes lumber for the building industry.', 7),
	('Paper Products', 'Manufacturers of all grades of paper. Excludes companies specializing in paper packaging classified in the Paper Packaging sub-industry.', 7),
	('Aerospace & Defense', 'Manufacturers of civil or military aerospace and defense equipment, parts or products. Includes defense electronics and space equipment.', 8),
	('Building Products', 'Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials sub-industry.', 9),
	('Construction & Engineering', 'Companies engaged in primarily non-residential construction. Includes civil engineering companies and large-scale contractors. Excludes companies classified in the Homebuilding sub-industry.', 10),
	('Electrical Components & Equipment', 'Companies that produce electric cables and wires, electrical components or equipment not classified in the Heavy Electrical Equipment sub-industry.', 11),
	('Heavy Electrical Equipment', 'Manufacturers of power-generating equipment and other heavy electrical equipment, including power turbines, heavy electrical machinery intended for fixed-use and large electrical systems. Excludes cables and wires, classified in the Electrical Components & Equipment sub-industry.', 11),
	('Industrial Conglomerates', 'Diversified industrial companies with business activities in three or more sectors, none of which contribute a majority of revenues. Stakes held are predominantly of a controlling nature, and stake holders maintain an operational interest in the running of the subsidiaries.', 12),
	('Construction Machinery & Heavy Trucks', 'Manufacturers of heavy duty trucks, rolling machinery, earth-moving and construction equipment, and manufacturers of related parts. Includes non-military shipbuilding.', 13),
	('Agricultural & Farm Machinery', 'Companies manufacturing agricultural machinery, farm machinery, and their related parts. Includes machinery used for the production of crops and agricultural livestock, agricultural tractors, planting and fertilizing machinery, fertilizer and chemical application equipment, and grain dryers and blowers.', 13),
	('Industrial Machinery', 'Manufacturers of industrial machinery and industrial components. Includes companies that manufacture presses, machine tools, compressors, pollution control equipment, elevators, escalators, insulators, pumps, roller bearings and other metal fabrications.', 13),
	('Trading Companies & Distributors', 'Trading companies and other distributors of industrial equipment and products.', 14),
	('Commercial Printing', 'Companies providing commercial printing services. Includes printers primarily serving the media industry.', 15),
	('Environmental & Facilities Services', 'Companies providing environmental and facilities maintenance services. Includes waste management, facilities management and pollution control services. Excludes large-scale water treatment systems classified in the Water Utilities sub-industry.', 15),
	('Office Services & Supplies', 'Providers of office services and manufacturers of office supplies and equipment not classified elsewhere.', 15),
	('Diversified Support Services', 'Companies primarily providing labor oriented support services to businesses and governments. Includes commercial cleaning services, dining & catering services, equipment repair services, industrial maintenance services, industrial auctioneers, storage & warehousing, transaction services, uniform rental services, and other business support services.', 15),
	('Security & Alarm Services', 'Companies providing security and protection services to business and governments. Includes companies providing services such as correctional facilities, security & alarm services, armored transportation & guarding. Excludes companies providing security software classified under the Systems Software sub-industry and home security services classified under the Specialized Consumer Services sub-industry. Also excludes companies manufacturing security system equipment classified under the Electronic Equipment & Instruments sub-industry.', 15),
	('Human Resource & Employment Services', 'Companies providing business support services relating to human capital management. Includes employment agencies, employee training, payroll & benefit support services, retirement support services and temporary agencies.', 16),
	('Research & Consulting Services', 'Companies primarily providing research and consulting services to businesses and governments not classified elsewhere. Includes companies involved in management consulting services, architectural design, business information or scientific research, marketing, and testing & certification services. Excludes companies providing information technology consulting services classified in the IT Consulting & Other Services sub-industry.', 16),
	('Air Freight & Logistics', 'Companies providing air freight transportation, courier and logistics services, including package and mail delivery and customs agents. Excludes those companies classified in the Airlines, Marine or Trucking sub-industries.', 17),
	('Airlines', 'Companies providing primarily passenger air transportation.', 18),
	('Marine', 'Companies providing goods or passenger maritime transportation. Excludes cruise ships classified in the Hotels, Resorts & Cruise Lines sub-industry.', 19),
	('Railroads', 'Companies providing primarily goods and passenger rail transportation.', 20),
	('Trucking', 'Companies providing primarily goods and passenger land transportation. Includes vehicle rental and taxi companies.', 20),
	('Airport Services', 'Operators of airports and companies providing related services.', 21),
	('Highways & Railtracks', 'Owners and operators of roads, tunnels and railtracks.', 21),
	('Marine Ports & Services', 'Owners and operators of marine ports and related services.', 21),
	('Auto Parts & Equipment', 'Manufacturers of parts and accessories for automobiles and motorcycles. Excludes companies classified in the Tires & Rubber sub-industry.', 22),
	('Tires & Rubber', 'Manufacturers of tires and rubber.', 22),
	('Automobile Manufacturers', 'Companies that produce mainly passenger automobiles and light trucks. Excludes companies producing mainly motorcycles and three-wheelers classified in the Motorcycle Manufacturers sub-industry and heavy duty trucks classified in the Construction & Farm Machinery & Heavy Trucks sub-industry.', 23),
	('Motorcycle Manufacturers', 'Companies that produce motorcycles, scooters or three-wheelers. Excludes bicycles classified in the Leisure Products sub-industry.', 23),
	('Consumer Electronics', 'Manufacturers of consumer electronics products including TVs, home audio equipment, game consoles,digital cameras, and related products. Excludes personal home computer manufacturers classified in the Technology Hardware,Storage & Peripherals Sub-Industry, and electric household appliances classified in the Household Appliances sub-industry.', 24),
	('Home Furnishings', 'Manufacturers of soft home furnishings or furniture, including upholstery, carpets and wall-coverings.', 24),
	('Homebuilding', 'Residential construction companies. Includes manufacturers of prefabricated houses and semi-fixed manufactured homes.', 24),
	('Household Appliances', 'Manufacturers of electric household appliances and related products. Includes manufacturers of power and hand tools, including garden improvement tools. Excludes TVs and other audio and video products classified in the Consumer Electronics sub-industry and personal computers classified in the Computer Hardware sub-industry.', 24),
	('Housewares & Specialties', 'Manufacturers of durable household products, including cutlery, cookware, glassware, crystal, silverware, utensils, kitchenware and consumer specialties not classified elsewhere.', 24),
	('Leisure Products', 'Manufacturers of leisure products and equipment including sports equipment, bicycles and toys.', 25),
	('Apparel, Accessories & Luxury Goods', 'Manufacturers of apparel, accessories and luxury goods. Includes companies primarily producing designer handbags, wallets, luggage, jewelry and watches. Excludes shoes classified in the Footwear sub-industry.', 26),
	('Footwear', 'Manufacturers of footwear. Includes sport and leather shoes.', 26),
	('Textiles', 'Manufacturers of textile and related products not classified in the Apparel, Accessories & Luxury Goods, Footwear or Home Furnishings sub-industries.', 26),
	('Casinos & Gaming', 'Owners and operators of casinos and gaming facilities. Includes companies providing lottery and betting services.', 27),
	('Hotels, Resorts & Cruise Lines', 'Owners and operators of hotels, resorts and cruise ships. Includes travel agencies, tour operators and related services not classified elsewhere. Excludes casino-hotels classified in the Casinos & Gaming sub-industry.', 27),
	('Leisure Facilities', 'Owners and operators of leisure facilities, including sport and fitness centers, stadiums, golf courses and amusement parks not classified in the Movies & Entertainment sub-industry.', 27),
	('Restaurants', 'Owners and operators of restaurants, bars, pubs, fast-food or take-out facilities. Includes companies that provide food catering services.', 27),
	('Education Services', 'Companies providing education services, either online or through conventional teaching methods. Includes private universities, correspondence teaching, providers of educational seminars, educational materials and technical education. Excludes companies providing employee education programs classified in the Human Resources & Employment Services sub-industry.', 28),
	('Specialized Consumer Services', 'Companies providing consumer services not classified elsewhere. Includes residential services, home security, legal services, personal services, renovation & interior design services, consumer auctions and wedding & funeral services.', 28),
	('Distributors', 'Distributors and wholesalers of general merchandise not classified elsewhere. Includes vehicle distributors.', 29),
	('Internet & Direct Marketing Retail', 'Companies providing retail services primarily on the internet, through mail order, and TV home shopping retailers. Also includes companies providing online marketplaces for consumer products and services.', 30),
	('Department Stores', 'Owners and operators of department stores.', 31),
	('General Merchandise Stores', 'Owners and operators of stores offering diversified general merchandise. Excludes hypermarkets and large-scale super centers classified in the Hypermarkets & Super Centers sub-industry.', 31),
	('Apparel Retail', 'Retailers specialized mainly in apparel and accessories.', 32),
	('Computer & Electronics Retail', 'Owners and operators of consumer electronics, computers, video and related products retail stores.', 32),
	('Home Improvement Retail', 'Owners and operators of home and garden improvement retail stores. Includes stores offering building materials and supplies.', 32),
	('Specialty Stores', 'Owners and operators of specialty retail stores not classified elsewhere. Includes jewelry stores, toy stores, office supply stores, health & vision care stores and book & entertainment stores.', 32),
	('Automotive Retail', 'Owners and operators of stores specializing in automotive retail. Includes auto dealers, gas stations, and retailers of auto accessories, motorcycles & parts, automotive glass and automotive equipment & parts.', 32),
	('Homefurnishing Retail', 'Owners and operators of furniture and home furnishings retail stores. Includes residential furniture, homefurnishings, housewares, and interior design. Excludes home and garden improvement stores, classified in the Home Improvement Retail sub-industry.', 32),
	('Drug Retail', 'Owners and operators of primarily drug retail stores and pharmacies.', 33),
	('Food Distributors', 'Distributors of food products to other companies and not directly to the consumer.', 33),
	('Food Retail', 'Owners and operators of primarily food retail stores.', 33),
	('Hypermarkets & Super Centers', 'Owners and operators of hypermarkets and super centers selling food and a wide-range of consumer staple products. Excludes Food and Drug Retailers classified in the Food Retail and Drug Retail sub-industries, respectively.', 33),
	('Brewers', 'Producers of beer and malt liquors. Includes breweries not classified in the Restaurants sub-industry.', 34),
	('Distillers & Vintners', 'Distillers, vintners and producers of alcoholic beverages not classified in the Brewers sub-industry.', 34),
	('Soft Drinks', 'Producers of non-alcoholic beverages including mineral waters. Excludes producers of milk classified in the Packaged Foods sub-industry.', 34),
	('Agricultural Products', 'Producers of agricultural products. Includes crop growers, owners of plantations and companies that produce and process foods but do not package and market them. Excludes companies classified in the Forest Products sub-industry and those that package and market the food products classified in the Packaged Foods & Meats sub-industry.', 35),
	('Packaged Foods & Meats', 'Producers of packaged foods including dairy products, fruit juices, meats, poultry, fish and pet foods.', 35),
	('Tobacco', 'Manufacturers of cigarettes and other tobacco products.', 36),
	('Household Products', 'Producers of non-durable household products, including detergents, soaps, diapers and other tissue and household paper products not classified in the Paper Products sub-industry.', 37),
	('Personal Products', 'Manufacturers of personal and beauty care products, including cosmetics and perfumes.', 38),
	('Health Care Equipment', 'Manufacturers of health care equipment and devices. Includes medical instruments, drug delivery systems, cardiovascular & orthopedic devices, and diagnostic equipment.', 39),
	('Health Care Supplies', 'Manufacturers of health care supplies and medical products not classified elsewhere. Includes eye care products, hospital supplies, and safety needle & syringe devices.', 39),
	('Health Care Distributors', 'Distributors and wholesalers of health care products not classified elsewhere.', 40),
	('Health Care Services', 'Providers of patient health care services not classified elsewhere. Includes dialysis centers, lab testing services, and pharmacy management services. Also includes companies providing business support services to health care providers, such as clerical support services, collection agency services, staffing services and outsourced sales & marketing services.', 40),
	('Health Care Facilities', 'Owners and operators of health care facilities, including hospitals, nursing homes, rehabilitation and retirement centers and animal hospitals.', 40),
	('Managed Health Care', 'Owners and operators of Health Maintenance Organizations (HMOs) and other managed plans.', 40),
	('Health Care Technology', 'Companies providing information technology services primarily to health care providers. Includes companies providing application, systems and/or data processing software, internet-based tools, and IT consulting services to doctors, hospitals or businesses operating primarily in the Health Care sector.', 41),
	('Biotechnology', 'Companies primarily engaged in the research, development, manufacturing and/or marketing of products based on genetic analysis and genetic engineering. Includes companies specializing in protein-based therapeutics to treat human diseases. Excludes companies manufacturing products using biotechnology but without a health care application.', 42),
	('Pharmaceuticals', 'Companies engaged in the research, development or production of pharmaceuticals. Includes veterinary drugs.', 43),
	('Life Sciences Tools & Services', 'Companies enabling the drug discovery, development and production continuum by providing analytical tools, instruments, consumables & supplies, clinical trial services and contract research services. Includes firms primarily servicing the pharmaceutical and biotechnology industries.', 44),
	('Diversified Banks', 'Large, geographically diverse banks with a national footprint whose revenues are derived primarily from conventional banking operations, have significant business activity in retail banking and small and medium corporate lending, and provide a diverse range of financial services. Excludes banks classified in the Regional Banks and Thrifts & Mortgage Finance Sub-Industries. Also excludes investment banks classified in the Investment Banking & Brokerage Sub-Industry.', 45),
	('Regional Banks', 'Commercial banks whose businesses are derived primarily from conventional banking operations and have significant business activity in retail banking and small and medium corporate lending. Regional banks tend to operate in limited geographic regions. Excludes companies in the Diversified Banks and Thrifts & Mortgage Banks sub-industries. Also excludes investment banks classified in the Investment Banking & Brokerage sub-industry.', 45),
	('Thrifts & Mortgage Finance', 'Financial institutions providing mortgage and mortgage related services. These include financial institutions whose assets are primarily mortgage related, savings & loans, mortgage lending institutions, building societies and companies providing insurance to mortgage banks.', 46),
	('Other Diversified Financial Services', 'Providers of a diverse range of financial services and/or with some interest in a wide range of financial services including banking, insurance and capital markets, but with no dominant business line. Excludes companies classified in the Regional Banks and Diversified Banks Sub-Industries.', 47),
	('Multi-Sector Holdings', 'A company with significantly diversified holdings across three or more sectors, none of which contribute a majority of profit and/or sales. Stakes held are predominantly of a non-controlling nature. Includes diversified financial companies where stakes held are of a controlling nature. Excludes other diversified companies classified in the Industrials Conglomerates sub-industry.', 47),
	('Specialized Finance', 'Providers of specialized financial services not classified elsewhere. Companies in this sub-industry derive a majority of revenue from one specialized line of business. Includes, but not limited to, commercial financing companies, central banks, leasing institutions, factoring services, and specialty boutiques. Excludes companies classified in the Financial Exchanges & Data sub-industry.', 47),
	('Consumer Finance', 'Providers of consumer finance services, including personal credit, credit cards, lease financing, travel-related money services and pawn shops. Excludes mortgage lenders classified in the Thrifts & Mortgage Finance sub-industry.', 48),
	('Asset Management & Custody Banks', 'Financial institutions primarily engaged in investment management and/or related custody and securities fee-based services. Includes companies operating mutual funds, closed-end funds and unit investment trusts. Excludes banks and other financial institutions primarily involved in commercial lending, investment banking, brokerage and other specialized financial activities.', 49),
	('Investment Banking & Brokerage', 'Financial institutions primarily engaged in investment banking and brokerage services, including equity and debt underwriting, mergers and acquisitions, securities lending and advisory services. Excludes banks and other financial institutions primarily involved in commercial lending, asset management and specialized financial activities.', 49),
	('Diversified Capital Markets', 'Financial institutions primarily engaged in diversified capital markets activities, including a significant presence in at least two of the following areas: large/major corporate lending, investment banking, brokerage and asset management. Excludes less diversified companies classified in the Asset Management & Custody Banks or Investment Banking & Brokerage sub-industries. Also excludes companies classified in the Banks or Insurance industry groups or the Consumer Finance sub-industry.', 49),
	('Financial Exchanges & Data', 'Financial exchanges for securities, commodities, derivatives and other financial instruments, and providers of financial decision support tools and products including ratings agencies.', 49),
	('Mortgage REITs', 'Companies or Trusts that service, originate, purchase and/or securitize residential and/or commercial mortgage loans. Includes trusts that invest in mortgage-backed securities and other mortgage related assets.', 50),
	('Insurance Brokers', 'Insurance and reinsurance brokerage firms.', 51),
	('Life & Health Insurance', 'Companies providing primarily life, disability, indemnity or supplemental health insurance. Excludes managed care companies classified in the Managed Health Care sub-industry.', 51),
	('Multi-line Insurance', 'Insurance companies with diversified interests in life, health and property and casualty insurance.', 51),
	('Property & Casualty Insurance', 'Companies providing primarily property and casualty insurance.', 51),
	('Reinsurance', 'Companies providing primarily reinsurance.', 51),
	('IT Consulting & Other Services', 'Providers of information technology and systems integration services not classified in the Data Processing & Outsourced Services or Internet Software & Services Sub-Industries. Includes information technology consulting and information management services.', 52),
	('Data Processing & Outsourced Services', 'Providers of commercial electronic data processing and/or business process outsourcing services. Includes companies that provide services for back-office automation.', 52),
	('Internet Services & Infrastructure', 'Companies providing services and infrastructure for the internet industry including data centers and cloud networking and storage infrastructure. Also includes companies providing web hosting services. Excludes companies classified in the Software Industry.', 52),
	('Application Software', 'Companies engaged in developing and producing software designed for specialized applications for the business or consumer market. Includes enterprise and technical software, as well as cloud-based software. Excludes companies classified in the Interactive Home Entertainment Sub-Industry. Also excludes companies producing systems or database management software classified in the Systems Software Sub-Industry.', 53),
	('Systems Software', 'Companies engaged in developing and producing systems and database management software.', 53),
	('Communications Equipment', 'Manufacturers of communication equipment and products, including LANs, WANs, routers, telephones, switchboards and exchanges. Excludes cellular phone manufacturers classified in the Technology Hardware, Storage & Peripherals Sub-Industry.', 54),
	('Technology Hardware, Storage & Peripherals', 'Manufacturers of cellular phones, personal computers, servers, electronic computer components and peripherals. Includes data storage components, motherboards, audio and video cards, monitors, keyboards, printers, and other peripherals. Excludes semiconductors classified in the Semiconductors Sub-Industry.', 55),
	('Electronic Equipment & Instruments', 'Manufacturers of electronic equipment and instruments including analytical, electronic test and measurement instruments.', 56),
	('Electronic Components', 'Manufacturers of electronic components. Includes electronic components, connection devices, electron tubes, electronic capacitors and resistors, electronic coil, printed circuit board, transformer and other inductors, signal processing technology/components and other electronic equipment not classified elsewhere.', 56),
	('Electronic Manufacturing Services', 'Producers of electronic equipment mainly for the OEM (Original Equipment Manufacturers) markets.', 56),
	('Technology Distributors', 'Distributors of technology hardware and equipment. Includes distributors of communications equipment, computers & peripherals, semiconductors, and electronic equipment and components.', 56),
	('Semiconductor Equipment', 'Manufacturers of semiconductor equipment.', 57),
	('Semiconductors', 'Manufacturers of semiconductors and related products.', 57),
	('Alternative Carriers', 'Providers of communications and high-density data transmission services primarily through a high bandwidth/fiber-optic cable network.', 58),
	('Integrated Telecommunication Services', 'Operators of primarily fixed-line telecommunications networks and companies providing both wireless and fixed-line telecommunications services not classified elsewhere. Also includes internet service providers offering internet access to end users.', 58),
	('Wireless Telecommunication Services', 'Providers of primarily cellular or wireless telecommunication services.', 59),
	('Advertising', 'Companies providing advertising, marketing or public relations services.', 60),
	('Broadcasting', 'Owners and operators of television or radio broadcasting systems, including programming. Includes radio and television broadcasting, radio networks, and radio stations.', 60),
	('Cable & Satellite', 'Providers of cable or satellite television services. Includes cable networks and program distribution.', 60),
	('Publishing', 'Publishers of newspapers, magazines and books in print or electronic formats.', 60),
	('Movies & Entertainment', 'Companies that engage in producing and selling entertainment products and services, including companies engaged in the production, distribution and screening of movies and television shows, producers and distributors of music, entertainment theaters and sports teams. Also includes companies offering and/or producing entertainment content streamed online.', 61),
	('Interactive Home Entertainment', 'Producers of interactive gaming products, including mobile gaming applications. Also includes educational software used primarily in the home. Excludes online gambling companies classified in the Casinos & Gaming Sub-Industry.', 61),
	('Interactive Media & Services', 'Companies engaging in content and information creation or distribution through proprietary platforms, where revenues are derived primarily through pay-per-click advertisements. Includes search engines, social media and networking platforms, online classifieds, and online review companies. Excludes companies operating online marketplaces classified in Internet & Direct Marketing Retail.', 62),
	('Electric Utilities', 'Companies that produce or distribute electricity. Includes both nuclear and non-nuclear facilities.', 63),
	('Gas Utilities', 'Companies whose main charter is to distribute and transmit natural and manufactured gas. Excludes companies primarily involved in gas exploration or production classified in Oil & Gas Exploration & Production sub-industry. Also excludes diversified midstream natural gas companies classified in the Oil & Gas Storage & Transportation sub-industry.', 64),
	('Multi-Utilities', 'Utility companies with significantly diversified activities in addition to core electric utility, gas utility and/or water utility operations.', 65),
	('Water Utilities', 'Companies that purchase and redistribute water to the end-consumer. Includes large-scale water treatment systems.', 66),
	('Independent Power Producers & Energy Traders', 'Companies that operate as Independent Power Producers (IPPs), Gas & Power Marketing & Trading Specialists and/or Integrated Energy Merchants. Excludes producers of electricity using renewable sources, such as solar power, hydropower, and wind power. Also excludes electric transmission companies and utility distribution companies classified in the Electric Utilities Sub-Industry.', 67),
	('Renewable Electricity', 'Companies that engage in generation and distribution of electricity using renewable sources, including, but not limited to, companies that produce electricity using biomass, geothermal energy, solar energy, hydropower, and wind power. Excludes companies manufacturing capital equipment used to generate electricity using renewable sources, such as manufacturers of solar power systems and installers of photovoltaic cells and companies involved in the provision of technology, components, and services mainly to this market.', 67),
	('Diversified REITs', 'Companies or trusts with significantly diversified operations across two or more property types.', 68),
	('Industrial REITs', 'Companies or trusts engaged in the acquisition, development, ownership, leasing, management and operation of industrial properties. Includes companies operating industrial warehouses and distribution properties.', 68),
	('Hotel & Resort REITs', 'Companies or trusts engaged in the acquisition, development, ownership, leasing, management and operation of hotel and resort properties.', 68),
	('Office REITs', 'Companies or trusts engaged in the acquisition, development, ownership, leasing, management and operation of office properties.', 68),
	('Health Care REITs', 'Companies or trusts engaged in the acquisition, development, ownership, leasing, management and operation of properties serving the health care industry, including hospitals, nursing homes, and assisted living properties.', 68),
	('Residential REITs', 'Companies or trusts engaged in the acquisition, development, ownership, leasing, management and operation of residential properties including multi-family homes, apartments, manufactured homes and student housing properties.', 68),
	('Retail REITs', 'Companies or trusts engaged in the acquisition, development, ownership, leasing, management and operation of shopping malls, outlet malls, neighborhood and community shopping centers.', 68),
	('Specialized REITs', 'Companies or trusts engaged in the acquisition, development, ownership, leasing, management and operation of properties not classified elsewhere. Includes trusts that operate and invest in storage properties. It also includes REITs that do not generate a majority of their revenues and income from real estate rental and leasing operations.', 68),
	('Diversified Real Estate Activities', 'Companies engaged in a diverse spectrum of real estate activities including real estate development & sales, real estate management, or real estate services, but with no dominant business line.', 69),
	('Real Estate Operating Companies', 'Companies engaged in operating real estate properties for the purpose of leasing & management.', 69),
	('Real Estate Development', 'Companies that develop real estate and sell the properties after development. Excludes companies classified in the Homebuilding sub-industry.', 69),
	('Real Estate Services', 'Real estate service providers such as real estate agents, brokers & real estate appraisers.', 69);
